import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'john',
      email: 'yuphop@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'jaden',
      email: 'info@how-fun.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocks: 20,
      description: 'A good Shirt',
    },
    {
      name: 'A Shirt',
      slug: 'a-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocks: 20,
      description: 'A good Shirt',
    },
    {
      name: 'B pants',
      slug: 'b-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocks: 20,
      description: 'A good Shirt',
    },
    {
      name: 'C Shirt',
      slug: 'c-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocks: 20,
      description: 'A good Shirt',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocks: 20,
      description: 'A good Shirt',
    },
  ],
};

export default data;
